<a href="https://colab.research.google.com/github/JoshiDeepak08/Machine_learning/blob/main/titanic_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [11]:
df= pd.read_csv('tested.csv')

In [12]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [13]:
df.shape

(418, 12)

In [14]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [15]:
df.drop(columns= ['Cabin','PassengerId','Ticket','Name'], inplace = True)

In [18]:
df.dropna()

     Survived  Pclass     Sex   Age  SibSp  Parch      Fare Embarked
0           0       3    male  34.5      0      0    7.8292        Q
1           1       3  female  47.0      1      0    7.0000        S
2           0       2    male  62.0      0      0    9.6875        Q
3           0       3    male  27.0      0      0    8.6625        S
4           1       3  female  22.0      1      1   12.2875        S
..        ...     ...     ...   ...    ...    ...       ...      ...
409         1       3  female   3.0      1      1   13.7750        S
411         1       1  female  37.0      1      0   90.0000        Q
412         1       3  female  28.0      0      0    7.7750        S
414         1       1  female  39.0      0      0  108.9000        C
415         0       3    male  38.5      0      0    7.2500        S

[331 rows x 8 columns]

In [19]:
df.duplicated().sum()

38

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  418 non-null    int64
 1   Pclass    418 non-null    int64
 2   Sex       418 non-null    object
 3   Age       332 non-null    float64
 4   SibSp     418 non-null    int64
 5   Parch     418 non-null    int64
 6   Fare      417 non-null    float64
 7   Embarked  418 non-null    object
dtypes: float64(2), int64(4), object(2)
memory usage: 26.2+ KB

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
x_train, x_test, y_train, y_test = train_test_split( df.drop(columns =['Survived']), df["Survived"], test_size = 0.2 , random_state= 42)

In [24]:
x_train.head()

     Pclass   Sex   Age  SibSp  Parch     Fare Embarked
336       2  male  32.0      0      0  13.0000        S
31        2  male  24.0      2      0  31.5000        S
84        2  male   NaN      0      0  10.7083        Q
287       1  male  24.0      1      0  82.2667        S
317       2  male  19.0      0      0  10.5000        S

In [32]:
# simple imputation
from sklearn.impute import SimpleImputer

si_age = SimpleImputer()
si_embarked = SimpleImputer(strategy= 'most_frequent')

x_train_age = si_age.fit_transform(x_train[['Age']])
x_train_embarked = si_embarked.fit_transform(x_train[['Embarked']])

x_test_age = si_age.transform(x_test[['Age']])
x_test_embarked = si_embarked.transform(x_test[['Embarked']])

In [37]:
from sklearn.preprocessing import OneHotEncoder
ohe_sex = OneHotEncoder(sparse = False)
ohe_embarked = OneHotEncoder(sparse = False)

x_train_sex = ohe_sex.fit_transform(x_train[['Sex']])
x_train_embarked= ohe_embarked.fit_transform(x_train_embarked)

x_test_sex =ohe_sex.transform(x_test[['Sex']])
x_test_embarked= ohe_embarked.transform(x_test_embarked)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

In [39]:
x_train_rem = x_train.drop( columns= ['Sex', 'Age', 'Embarked'])
x_test_rem = x_test.drop( columns= ['Sex', 'Age', 'Embarked'])

In [58]:
x_train_trans = np.concatenate((x_train_rem, x_train_age, x_train_embarked, x_train_sex), axis = 1)
x_test_trans = np.concatenate((x_test_age, x_test_rem , x_test_embarked, x_test_sex),axis= 1)

In [59]:
from sklearn.tree import DecisionTreeClassifier

In [60]:
clf= DecisionTreeClassifier()
clf.fit( x_train_trans, y_train)

DecisionTreeClassifier()

In [61]:
y_pred = clf.predict(x_test_trans)

In [62]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

1.0